package com.Wsdl2Code.WebServices.ServiceMobile;

//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.6
//
// Date Of Creation: 6/24/2015 6:28:23 PM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//
import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;

import java.io.Serializable;
import java.util.Hashtable;

import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

public class TaskDto implements KvmSerializable, Serializable {
    
    public String jobId;
    public String recruiteeId;
    public String taskDescription;
    public String taskId;
    
    public TaskDto(){}
    
    public TaskDto(SoapObject soapObject)
    {
        if (soapObject == null)
            return;
        if (soapObject.hasProperty("JobId"))
        {
            Object obj = soapObject.getProperty("JobId");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                jobId = j.toString();
            }else if (obj!= null && obj instanceof String){
                jobId = (String) obj;
            }
        }
        if (soapObject.hasProperty("RecruiteeId"))
        {
            Object obj = soapObject.getProperty("RecruiteeId");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                recruiteeId = j.toString();
            }else if (obj!= null && obj instanceof String){
                recruiteeId = (String) obj;
            }
        }
        if (soapObject.hasProperty("TaskDescription"))
        {
            Object obj = soapObject.getProperty("TaskDescription");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                taskDescription = j.toString();
            }else if (obj!= null && obj instanceof String){
                taskDescription = (String) obj;
            }
        }
        if (soapObject.hasProperty("TaskId"))
        {
            Object obj = soapObject.getProperty("TaskId");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                taskId = j.toString();
            }else if (obj!= null && obj instanceof String){
                taskId = (String) obj;
            }
        }
    }
    @Override
    public Object getProperty(int arg0) {
        switch(arg0){
            case 0:
                return jobId;
            case 1:
                return recruiteeId;
            case 2:
                return taskDescription;
            case 3:
                return taskId;
        }
        return null;
    }
    
    @Override
    public int getPropertyCount() {
        return 4;
    }
    
    @Override
    public void getPropertyInfo(int index, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
        switch(index){
            case 0:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "JobId";
                break;
            case 1:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "RecruiteeId";
                break;
            case 2:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "TaskDescription";
                break;
            case 3:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "TaskId";
                break;
        }
    }

    
    @Override
    public void setProperty(int arg0, Object arg1) {
    }
    
}
